### PR TITLE
Add results for Darien 2016 presidential election

### LINKED ISSUE #1: Convert town-level results to CSV
For Connecticut town-level results, our CSV files should have the following headers:

`county`, `town`, `precinct`,`office`, `district`, `party`, `candidate`, `votes`

With one line per candidate result per precinct. Here's [an example from Massachusetts](https://github.com/openelections/openelections-data-ma/blob/master/2016/20161108__ma__general__brookline__precinct.csv).

The CSV files should be named `YYMMDD__ct__{election_type}__{town}__precinct.csv`

### PR DESCRIPTION
**Pull request by brianloveswords**
Fixes #1 

I noticed that it included the comma separators for the number in vote counts, if that's a problem I can re-export it and remove those.

### CODE REVIEW

**Comment by dwillis** [comment]
@brianloveswords I should have mentioned that - it would be great to remove those.

**Comment by brianloveswords** [comment]
No problem, updating incoming.

**Comment by brianloveswords** [comment]
@dwillis commas removed

**Comment by dwillis** [comment]
Thanks @brianloveswords!

**Pull request merged**
